backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images/posts"
public_folder: "/images/posts"

logo_url: "https://pervoj.github.io/nuclear/assets/logos/default-dark.svg"

collections:

  - name: "blog-en"
    label: "Blog (en)"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slugurl}}"
    filter:
      field: lang
      value: en
    fields:
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slugurl", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", time_format: false }
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog-cs"
    label: "Blog (cs)"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slugurl}}.cs"
    filter:
      field: lang
      value: cs
    fields:
      - { label: "Language", name: "lang", widget: "hidden", default: "cs" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slugurl", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", time_format: false }
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
