backend:
  name: git-gateway
  branch: main

media_folder: "static/images/posts"
public_folder: "/images/posts"

collections:

  - name: "blog-en"
    label: "Blog (en)"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    filter:
      field: lang
      value: en
    fields:
      - { label: "Language", name: "lang", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "extra.description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog-cs"
    label: "Blog (cs)"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.cs"
    filter:
      field: extra.lang
      value: cs
    fields:
      - { label: "Language", name: "lang", widget: "hidden", default: "cs" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "extra.description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Extra"
        name: "extra"
        widget: "object"
        fields:
          - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
